apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: todo-app
data:
  POSTGRES_DB: todo_db
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: todo-app
type: Opaque
data:
  POSTGRES_USER: cG9zdGdyZXM=  # postgres in base64
  POSTGRES_PASSWORD: cG9zdGdyZXM=  # postgres in base64
  POSTGRES_DB: dG9kb19kYg==  # todo_db in base64